export enum MedicalSpecialty {
  ALLERGOLOGY = "Allergology",
  ANESTHESIOLOGY = "Anesthesiology",
  ANGIOLOGY = "Angiology",
  ONCOLOGY = "Oncology",
  CARDIOLOGY = "Cardiology",
  CARDIOVASCULAR_SURGERY = "Cardiovascular Surgery",
  HEAD_AND_NECK_SURGERY = "Head and Neck Surgery",
  DIGESTIVE_SURGERY = "Digestive System Surgery",
  GENERAL_SURGERY = "General Surgery",
  PEDIATRIC_SURGERY = "Pediatric Surgery",
  PLASTIC_SURGERY = "Plastic Surgery",
  THORACIC_SURGERY = "Thoracic Surgery",
  VASCULAR_SURGERY = "Vascular Surgery",
  INTERNAL_MEDICINE = "Internal Medicine",
  DERMATOLOGY = "Dermatology",
  ENDOCRINOLOGY = "Endocrinology and Metabolism",
  ENDOSCOPY = "Endoscopy",
  GASTROENTEROLOGY = "Gastroenterology",
  GERIATRICS = "Geriatrics",
  OBSTETRICS_AND_GYNECOLOGY = "Obstetrics and Gynecology",
  HEMATOLOGY = "Hematology and Hemotherapy",
  HEPATOLOGY = "Hepatology",
  HOMEOPATHY = "Homeopathy",
  INFECTIOUS_DISEASES = "Infectious Diseases",
  MASTOLOGY = "Mastology (Breast Surgery)",
  EMERGENCY_MEDICINE = "Emergency Medicine",
  SPORTS_MEDICINE = "Sports Medicine",
  OCCUPATIONAL_MEDICINE = "Occupational Medicine",
  FAMILY_MEDICINE = "Family and Community Medicine",
  PHYSICAL_MEDICINE_REHABILITATION = "Physical Medicine and Rehabilitation",
  INTENSIVE_CARE_MEDICINE = "Intensive Care Medicine",
  LEGAL_MEDICINE = "Legal and Forensic Medicine",
  NEPHROLOGY = "Nephrology",
  NEUROSURGERY = "Neurosurgery",
  NEUROLOGY = "Neurology",
  NUTROLOGY = "Nutrition Medicine",
  OPHTHALMOLOGY = "Ophthalmology",
  CLINICAL_ONCOLOGY = "Clinical Oncology",
  ORTHOPEDICS_TRAUMATOLOGY = "Orthopedics and Traumatology",
  OTORHINOLARYNGOLOGY = "Otorhinolaryngology (ENT)",
  PATHOLOGY = "Pathology",
  CLINICAL_PATHOLOGY = "Clinical Pathology/Laboratory Medicine",
  PEDIATRICS = "Pediatrics",
  PULMONOLOGY = "Pulmonology",
  PSYCHIATRY = "Psychiatry",
  RADIOLOGY = "Radiology and Imaging Diagnostics",
  RADIOTHERAPY = "Radiation Oncology",
  RHEUMATOLOGY = "Rheumatology",
  UROLOGY = "Urology",
}

export const medicalSpecialties = Object.entries(MedicalSpecialty).map(
  ([key, value]) => ({
    value: MedicalSpecialty[key as keyof typeof MedicalSpecialty],
    label: value,
  }),
);
